version: "3.9"
services:
  postgresdb:
    networks: 
      - multiple_choice
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Abc@123
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
networks:
  multiple_choice: