version: '3.3'
services:
  app:
    image: create-quiz-service:latest
    restart: always
    container_name: create-quiz-service
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - EUREKA_URL=${EUREKA_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - FE_HOST=${FE_HOST}
    ports:
      - "8080:8080"
    network_mode: "host"