version: '3.3'
services:
  user-service:
    image: user-service:latest
    restart: unless-stopped
    container_name: user-service
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/quiz_lab?createDatabaseIfNotExist=true
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=Abc@123
      # - EUREKA_URL=http://localhost:8761/eureka
    ports:
      - "8081:8081"
    networks:
      - multiple_choice
networks:
  multiple_choice: