version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/root/redis
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=Abc@123
      - REDIS_PORT=6379
      - REDIS_DATABASES=quiz-lab
volumes:
  redis-data: